"""
Configuration for Dog Groomer Locator Directory
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base Paths
BASE_DIR = Path(__file__).parent
TEMPLATES_DIR = BASE_DIR / "templates"
STATIC_DIR = BASE_DIR / "static"
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "dist"

# Site Configuration
SITE_NAME = "Dog Groomer Locator"
SITE_DESCRIPTION = "Find trusted dog groomers near you. Browse ratings, services, prices, and reviews for professional pet grooming across America."
SITE_URL = os.getenv("SITE_URL", "https://doggroomerlocator.com")
SITE_AUTHOR = "Dog Groomer Locator"
DEFAULT_OG_IMAGE = "/static/images/og-image.png"

# Airtable Configuration
AIRTABLE_API_KEY = os.getenv("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.getenv("AIRTABLE_BASE_ID")
AIRTABLE_TABLE_NAME = os.getenv("AIRTABLE_TABLE_NAME", "Groomers")
AIRTABLE_BLOG_TABLE_NAME = os.getenv("AIRTABLE_BLOG_TABLE_NAME", "Blog Posts")

# Monetization
ADSENSE_CLIENT_ID = os.getenv("ADSENSE_CLIENT_ID", "ca-pub-9265762311868507")
ADSENSE_ENABLED = os.getenv("ADSENSE_ENABLED", "false").lower() in {"1", "true", "yes", "on"}

# Noindex Thresholds — content-quality gating
MIN_STATE_LISTINGS_FOR_INDEX = 3   # State pages with fewer listings get noindex
MIN_CITY_LISTINGS_FOR_INDEX = 10   # City pages with fewer listings get noindex
                                   # Higher than state because city pages duplicate listings
                                   # already on the state page; they need volume to justify
                                   # a separate indexed URL.
MIN_DESCRIPTION_LENGTH = 300       # Listing description minimum chars for indexing
CATEGORY_PREVIEW_LIMIT = 120       # Prevent category pages from becoming huge listing dumps
REPETITIVE_DESCRIPTION_START_WORDS = 8
REPETITIVE_DESCRIPTION_MAX_REPEATS = 3

# Description quality filters — listing is noindexed if its description matches
# any junk pattern, lacks any grooming-related vocabulary, or is too short.
# This catches scraped/corrupted descriptions (e.g. tattoo studio metadata leaking
# into a groomer record) that pass simple "is data present" checks.
JUNK_DESCRIPTION_TERMS = [
    "tattoo", "piercing", "reeperbahn", "talstrasse",
    "@bibo_", "@drmrgowda", "ffnungszeiten",  # observed scraped patterns
    " br br ", " br ", "<br",  # leaked HTML markup as plain text
    "jetzt anrufen", "klicken sie", "horario:",  # non-English markers from scrapes
]
GROOMING_VOCAB = [
    "groom", "dog", "pet", "puppy", "salon", "spa",
    "bath", "cut", "trim", "nail", "coat", "fur", "wash",
    "shampoo", "brush", "clip", "shed", "shedding",
    "boutique", "kennel", "hound", "canine", "animal", "k9", "k-9",
]

# Authors — E-E-A-T: each blog post must have a credited author with credentials
AUTHORS = {
    "sarah-mitchell": {
        "name": "Sarah Mitchell",
        "credentials": "Certified Master Groomer (CMG), International Professional Groomers Inc.",
        "bio": "Sarah Mitchell is a Certified Master Groomer with over 15 years of experience in professional pet grooming. She has worked with all breeds from toy poodles to giant schnauzers and specializes in breed-specific styling and coat health. Sarah writes about grooming techniques, coat care, and choosing the right groomer for your dog.",
        "headshot": "",
    },
    "dog-groomer-locator-staff": {
        "name": "Dog Groomer Locator Staff",
        "credentials": "Pet care research team",
        "bio": "The Dog Groomer Locator editorial team researches and verifies grooming businesses across the United States, helping dog owners find trusted local groomers with transparent pricing, honest reviews, and professional credentials.",
        "headshot": "",
    },
}
DEFAULT_AUTHOR_KEY = "sarah-mitchell"

# US States for state-based pages
US_STATES = [
    {"name": "Alabama", "slug": "alabama", "abbr": "AL",
     "description": "Alabama's grooming community spans the Gulf Coast humidity of Mobile, the rolling foothills around Birmingham and Huntsville, and the river towns along the Tennessee and Alabama rivers. The state's mixed dog population — bird hunters working coveys in the south, family pets in the metro suburbs, and show-line German Shorthaired Pointers and Boykin Spaniels in between — keeps groomers experienced with everything from quick field rinses to breed-standard cuts. Year-round humidity is the dominant grooming consideration: heavy double coats trap moisture and lead to hot spots, yeast issues, and skin irritation that needs medicated shampoos and careful blow-drying. Many Alabama groomers offer summer-clip packages from late April through October, and full deshedding sessions peak twice a year as winter and summer coats blow. Pricing tends to run lower than the national average, with most full-service grooms in the $40–$70 range for medium dogs and mobile services and breed-specific styling sitting at the higher end. Birmingham and Huntsville have the densest concentrations of professional salons and several mobile-grooming vans serving outlying suburbs; smaller towns from Decatur to Dothan are typically served by single-operator salons or independent groomers working out of veterinary clinics. If you're new to the area, look for groomers who can talk specifically about humidity-related coat care, hot-spot prevention, and conditioner choices for double-coated breeds — that's a meaningful Alabama signal of someone who actually understands the local climate, not just someone running through a generic full-service checklist."},
    {"name": "Alaska", "slug": "alaska", "abbr": "AK",
     "description": "Grooming in Alaska is shaped by extremes. Most dogs in the state carry thick double coats — Huskies, Malamutes, Akitas, Newfoundlands, German Shepherds, plus the working sled breeds that still pull in mushing communities — and those coats need professional care that flat-coated dogs in warmer states never demand. Anchorage, Fairbanks, Wasilla, and Juneau anchor the state's grooming industry, with smaller communities like Kenai, Soldotna, and Sitka served by mobile groomers who travel substantial distances between appointments. Spring and fall are the heaviest grooming seasons. Coat blow — when the dense undercoat releases in handfuls — happens twice a year, and Alaskan groomers are uniformly experienced with high-velocity dryers, undercoat rakes, and the multi-hour deshedding sessions that double-coated dogs require. Cutting or shaving double coats is generally avoided here; reputable groomers will counsel against shave-downs even in summer, since the undercoat insulates against heat as well as cold. Paw care is also a year-round concern: ice balls in winter, hot pavement in the brief summer, and salt or chemical de-icers on city streets all require regular paw pad inspection and trimming. Pricing in Alaska is among the highest in the country — reflecting fewer groomers per capita, the time required for double-coat work, and the cost of operating in remote markets. Many Alaska groomers also offer specialty services around hunting and sledding seasons, including post-trip rinses, scent removal, and burr/seed extraction. Mobile groomers in the road-belt areas often book months ahead."},
    {"name": "Arizona", "slug": "arizona", "abbr": "AZ",
     "description": "Arizona's grooming industry is built around desert climate management. The Phoenix metro — Scottsdale, Tempe, Mesa, Chandler, Glendale, Surprise, and Gilbert — supports one of the densest concentrations of full-service salons and mobile groomers in the Southwest. Tucson, Flagstaff, Prescott, Sedona, and Yuma round out the regional markets, each with its own climate considerations: low desert in the south, high desert and mountain communities in the north, river-valley humidity along the Colorado. Heat is the central grooming concern. Pavement temperatures can exceed 150°F in summer, which makes paw pad trimming, post-walk paw rinsing, and protective wax treatments standard add-ons at most Arizona salons. Summer cooling clips are common, but reputable groomers will refuse to shave down double-coated breeds — the undercoat protects from heat as much as cold, and a shaved Husky or Malamute is more vulnerable, not less, in 110°F weather. What you'll see instead is aggressive deshedding, sanitary trims, and shorter face/feet/tail blends. Dry-skin care also distinguishes Arizona grooming. Low humidity year-round causes flaking, dandruff, and static, so most local groomers stock conditioning shampoos and leave-in moisturizers specifically for desert dogs. Allergy season — peak desert pollen runs from late winter through early summer — brings demand for hypoallergenic baths and oatmeal soaks. Pricing in metro Phoenix runs the gamut from budget chain grooming at the low end to high-touch mobile services in Scottsdale and Paradise Valley at the premium end. Smaller towns and the West Valley tend toward independent salons with mid-tier pricing."},
    {"name": "Arkansas", "slug": "arkansas", "abbr": "AR",
     "description": "Arkansas's grooming industry reflects the state's split personality — urban professional salons in Little Rock, North Little Rock, and the Northwest Arkansas corridor of Fayetteville, Bentonville, Rogers, and Springdale, paired with smaller-town independents serving the Ozark and Ouachita regions, the Mississippi Delta, and South Arkansas. Hot Springs and Fort Smith add additional regional clusters. Hunting dogs are a meaningful share of the Arkansas grooming market. Labradors, Beagles, Walkers, Plotts, and various pointing breeds come in regularly during and after duck, deer, and small-game seasons for post-field cleaning: burr extraction, tick checks, gland expression, ear cleaning, and full bath-and-blow services to clear out brush debris. Several Arkansas groomers specialize in this work and offer same-week post-hunt appointments. Family-pet grooming covers the same range as the rest of the country — full-service grooms, breed cuts, mobile services, self-service washes — with the Northwest Arkansas tech corridor supporting some of the higher-end mobile and boutique grooming offerings. The climate runs hot and humid in summer with mild winters, which means moderate seasonal variation in grooming demand. Tick prevention runs nearly year-round in southern Arkansas; flea pressure is constant statewide. Many groomers stock medicated shampoos for the hot-spot and yeast issues that accompany humid summers. Pricing in Arkansas tends toward the lower end of the national range — full-service grooms commonly fall between $35 and $60 for medium dogs, with mobile services running $20–$30 higher. Northwest Arkansas pricing trends slightly upward thanks to the region's higher cost of living and growing pet-care market."},
    {"name": "California", "slug": "california", "abbr": "CA",
     "description": "California has the largest dog-grooming market in the United States, and it's not close. From luxury Beverly Hills mobile services and West Hollywood boutique salons to neighborhood shops in Sacramento, San Diego, Fresno, and Bakersfield, the state supports thousands of grooming businesses across nearly every operating model — full-service salons, mobile vans, self-service washes, breed-specialty studios, and integrated pet-care facilities that combine grooming with daycare, training, and veterinary services. Regional variation is significant. Coastal Southern California — Los Angeles, Orange County, San Diego — leans toward boutique mobile services, premium pricing ($90–$200+ for full-service grooming on small dogs), and trend-driven offerings like blueberry facials, paw mani-pedis, and creative coloring. The Bay Area follows a similar premium pattern, with San Francisco, Oakland, and the Peninsula supporting some of the country's highest-end grooming spas. Sacramento and the Central Valley operate at more accessible price points, with strong independent salons across Fresno, Modesto, Stockton, and Bakersfield. The Inland Empire and Riverside County have a mix of chain grooming and independents serving a fast-growing population. Climate considerations vary by region too. Coastal dogs deal with marine layer humidity and fog-related skin issues; Central Valley summers push toward summer-clip cycles; mountain and high-desert communities (Big Bear, Mammoth, Lake Tahoe) handle thick-coated breeds suited to their elevation. California's strong year-round outdoor culture means most dogs stay active year-round, which keeps grooming demand consistent. Mobile grooming is particularly well-developed across the state, especially in dense urban areas where parking and travel time push owners toward at-home service."},
    {"name": "Colorado", "slug": "colorado", "abbr": "CO",
     "description": "Colorado's grooming industry is shaped by the state's outdoor culture more than its climate. Dogs in Denver, Boulder, Fort Collins, Colorado Springs, and the Front Range mountain towns spend a significant portion of their lives on trails, in snow, in mud, in mountain creeks, and on summer alpine hikes — all of which translates into a consistent demand for professional bath-and-deshedding services and regular paw and pad maintenance. Double-coated breeds are heavily represented: Bernese Mountain Dogs, Australian Shepherds, Border Collies, Huskies, Golden Retrievers, and the regional favorite Labradoodles and Goldendoodles all show up in significant numbers at Colorado salons. Altitude and dry mountain air drive a few specific grooming needs that aren't as common elsewhere. Static, dry skin, and dandruff are persistent issues; reputable Colorado groomers carry humectant conditioners and oat-based moisturizers as standard. Sunburn on light-skinned breeds (white Shepherds, Dalmatians, Pit-mix breeds with pink ears) is more common at high elevation, so summer cuts on those dogs typically leave more coat than they would at sea level. Mud season — late spring snowmelt — is the busiest time of year for many Front Range groomers, particularly mobile operators who cover the suburban Denver corridor and the foothill communities like Evergreen, Conifer, and Castle Rock. Pricing across Colorado tends to skew premium in Boulder, Denver Highlands, and ski-town markets like Vail and Aspen, with more accessible rates in Pueblo, Greeley, and the Western Slope. Mobile grooming is well-established statewide, particularly in suburbs where street parking is constrained."},
    {"name": "Connecticut", "slug": "connecticut", "abbr": "CT",
     "description": "Connecticut packs a substantial grooming industry into a small geography. The Gold Coast — Greenwich, Westport, New Canaan, Darien, Stamford — supports some of the highest-end mobile grooming services in the Northeast, with prices that rival Manhattan boutique salons. Hartford, New Haven, Bridgeport, Waterbury, and Norwich anchor mid-tier metro markets, and the Litchfield Hills and Eastern Connecticut towns are served by a mix of independent salons and mobile groomers covering wider routes. Connecticut's seasons drive a clear grooming calendar. Spring deshedding peaks in March and April for double-coated breeds. Summer brings demand for cooling clips on Goldens, Bernese, and Newfoundlands — though most Connecticut groomers will only blend coats, not shave them, on these breeds. Fall is the ticks-and-burrs season for hunting dogs and trail-active suburban pets, and many groomers offer extraction services and post-hunt full-service packages. Winter brings salt-on-paw care: salt and chemical de-icers on suburban driveways and sidewalks irritate paw pads and dry out coats, so paw rinses, balm applications, and conditioning bath upgrades are common winter add-ons. The Connecticut Shore communities — Old Saybrook, Madison, Mystic — see a noticeable seasonal demand spike during summer and around fall foliage tourism. Mobile grooming is unusually well-developed for a small state, partly because the dense suburban geography keeps drive times reasonable and many homeowners value the convenience. Pricing varies dramatically across the state — full-service grooming on a medium dog can run $50 in Waterbury and $150 in Greenwich for nearly identical work."},
    {"name": "Delaware", "slug": "delaware", "abbr": "DE",
     "description": "Delaware is the second-smallest state in the country, but its grooming industry punches above that weight thanks to two strong markets stacked on top of each other: the Wilmington-Newark corridor in New Castle County, which functions as a Philadelphia-area extension, and the Rehoboth Beach-Lewes-Bethany Beach beach communities, which see seasonal demand spikes that wash through the entire summer. Dover, Smyrna, and Middletown serve the central Kent County corridor; Seaford, Georgetown, and Milford anchor the Sussex County interior. New Castle County grooming pricing tends to align with Greater Philadelphia rates: $60–$120 for full-service grooms on medium dogs, with mobile services running higher and breed-specific styling at the top of the range. Beach communities run premium during summer — partly due to seasonal demand, partly because vacation-home owners with dogs often book reactive grooming appointments after beach visits to deal with sand, salt water, and the seasonal flea pressure that comes with dunes and beach grass. The mid-Atlantic climate brings four distinct seasons but moderated by Atlantic proximity. Spring and fall are the heaviest deshedding seasons; humid summers drive demand for medicated baths and hot-spot treatments; winters are mild compared to states further north but still include salt-on-paw care from suburban roads. Many Delaware groomers offer add-on services that reflect the older-skewing population in retirement-heavy Sussex County: gentle handling for arthritic seniors, padded grooming tables, shorter-session breakouts, and communication with vets about age-related skin or coat conditions."},
    {"name": "Florida", "slug": "florida", "abbr": "FL",
     "description": "Florida has one of the largest dog grooming markets in the country, driven by year-round warmth, one of the highest pet ownership rates in the nation, and a population that skews older — meaning more senior dogs that need regular professional grooming. Miami-Dade and Broward, the Tampa Bay area, Orlando, Jacksonville, and the Naples–Fort Myers corridor each support hundreds of grooming businesses, with The Villages, Sarasota, and the Space Coast adding additional senior-heavy markets. Year-round subtropical humidity defines Florida grooming. Hot-spot prevention, yeast and bacterial skin issue treatment, and flea-and-tick control are constants rather than seasonal concerns. Most Florida groomers stock medicated shampoos as first-line products, not specialty add-ons, and many offer add-on flea baths and tick checks as standard. Summer cooling clips are common but selective — double-coated breeds get aggressive deshedding rather than shave-downs. Salt-water and pool-chlorine rinses are common services in coastal and swimming-pool-heavy markets. The senior-dog skew of Florida's pet population shapes the service mix: many groomers explicitly market arthritis-friendly handling, padded tables, shorter sessions, and gentle handling for senior dogs and dogs with mobility issues. Mobile grooming is unusually popular for that reason — house calls reduce the stress and travel difficulty for older pets. Pricing varies widely by region. Miami, Naples, and the higher-end Gulf Coast retirement communities run premium ($70–$150+ for medium full-service grooming); Jacksonville, Orlando suburbs, and inland markets are more accessible ($45–$90). Mobile services typically add $20–$40 over salon pricing across the state."},
    {"name": "Georgia", "slug": "georgia", "abbr": "GA",
     "description": "Georgia's grooming industry is anchored by Atlanta's massive metro footprint — the dense Buckhead, Midtown, and Decatur boutique markets, the family-pet salons of Marietta, Alpharetta, Roswell, and Sandy Springs, and the suburban-mobile-grooming corridor that runs through Cobb, Gwinnett, and Fulton counties. Outside the ATL metro, Savannah supports a distinct coastal grooming community shaped by humidity and historic-district pet ownership; Augusta, Columbus, Macon, and Athens each anchor regional clusters; and the North Georgia mountain towns from Dahlonega to Ellijay serve a growing population of weekenders and second-home owners with dogs. Heat and humidity are the dominant climate factors. Atlanta summers are brutal for double-coated breeds, and the state's heavy oak pollen — peak around late March and April — drives a noticeable spike in grooming demand for allergy-related skin issues, hypoallergenic baths, and oatmeal soaks. Hot-spot prevention runs nearly year-round in southern Georgia. Tick exposure peaks in spring and fall, and many groomers offer same-day post-trip tick checks for dogs returning from north Georgia mountains or the coast. Pricing in metro Atlanta runs the full range — from chain grooming at $45 to high-end mobile and Buckhead boutique services pushing past $150 for medium dogs. Outside the metro, full-service grooms in the $40–$70 range are standard. Mobile grooming is well-developed in Atlanta's outer suburbs, where long drives to a salon and limited parking make in-home service especially attractive."},
    {"name": "Hawaii", "slug": "hawaii", "abbr": "HI",
     "description": "Hawaii's grooming industry is small but specialized — shaped by the islands' tropical climate, salt-air exposure, the cost and complexity of importing pets and supplies, and a strong pet-care culture across both local and transplant populations. Honolulu, Pearl City, Kailua, and the rest of Oahu support the densest concentration of salons; Maui (Kahului, Wailuku, Kihei, Lahaina), the Big Island (Hilo, Kona), and Kauai (Lihue, Kapaa) each have smaller but dedicated grooming communities. Island-specific climate considerations dominate the work. Year-round humidity and salt air drive aggressive coat-care routines: salt-water rinses after beach trips, hot-spot prevention shampoos, anti-fungal treatments for the yeast issues that thrive in tropical climates, and dehumidifying coat conditioning for dogs that swim regularly. Sun exposure is intense and year-round, so summer-style cuts that leave protective coat are preferred for dogs with light skin or thin coats. Tropical grasses bring foxtail and seed-pod issues; coastal sand drives ear and paw rinses. Hawaii's history of strict pet quarantine has shifted in recent years to a streamlined direct-release program, but the legacy means the dog population on the islands is somewhat smaller and more carefully chosen than mainland averages, with a noticeable share of Shibas, Pugs, French Bulldogs, and other breeds well-suited to apartment living. Pricing on Hawaii runs higher than mainland averages — partly the cost of doing business on the islands, partly the limited supply of professional groomers. Mobile services exist but are less common than on the mainland."},
    {"name": "Idaho", "slug": "idaho", "abbr": "ID",
     "description": "Idaho's grooming industry has grown substantially over the past decade, tracking the population boom in the Treasure Valley and the broader migration into the state. Boise, Meridian, Nampa, Caldwell, and Eagle anchor the largest market by far, with Idaho Falls, Pocatello, and Twin Falls serving the Eastern Idaho corridor and Coeur d'Alene, Post Falls, and Sandpoint covering North Idaho. The Sun Valley–Ketchum area supports a small but premium-priced grooming community shaped by second-home owners and the resort economy. Idaho dogs see a lot of outdoor work — hunting, ranching, hiking, river time, and ski-country activity — and grooming demand reflects that. Post-trip services are a meaningful share of the market: burr extraction, full bath-and-blow services to clear out brush and debris, paw pad inspection for thorns and cuts, and ear cleaning after water exposure. Tick prevention is significant, particularly in the foothills and forested areas. Double-coated breeds — Aussies, Border Collies, Goldens, Bernese, Huskies — are heavily represented and drive consistent demand for spring and fall deshedding. Climate considerations vary widely across the state. Boise summers are hot and dry; Northern Idaho carries Pacific Northwest moisture; mountain communities deal with snow, ice, and dry winter air. Most experienced Idaho groomers stock conditioning shampoos for dry coats and offer scheduled deshedding packages timed to the typical coat-blow cycles. Pricing across Idaho runs more accessibly than coastal-state averages, with most full-service grooms in the $45–$80 range. Mobile grooming has expanded rapidly in the Treasure Valley over the last few years."},
    {"name": "Illinois", "slug": "illinois", "abbr": "IL",
     "description": "Illinois's grooming industry is dominated by the Chicago metropolitan area — one of the most dog-friendly major cities in the country and home to thousands of grooming professionals across nearly every operating model. The Loop, Lincoln Park, Lakeview, Wicker Park, Logan Square, and the North Shore (Evanston, Wilmette, Glenview, Highland Park) collectively support some of the densest urban grooming infrastructure in the U.S. The Western suburbs (Naperville, Wheaton, Oak Park, Hinsdale), Southwest suburbs (Orland Park, Tinley Park), and Northwest suburbs (Schaumburg, Arlington Heights, Palatine) add hundreds more salons and mobile operators. Outside Chicagoland, Rockford, Peoria, Springfield, Bloomington-Normal, Champaign-Urbana, and the Metro East communities across from St. Louis each anchor regional grooming markets, and downstate Illinois has a long tradition of independent salons and farm-adjacent groomers. Chicago winters drive a specific set of grooming demands. Salt and chemical de-icers are used aggressively on city sidewalks, parking garages, and arterial streets, and they are hard on paw pads. Most Chicago groomers offer paw rinses, paw balm applications, and sanitary trims for dogs that pick up salt slush in their belly fur. Spring deshedding for double-coated breeds is heavy after Chicago winters, and summer humidity drives demand for hot-spot treatments and medicated baths. Pricing in Chicago runs the full range — from neighborhood Petco/PetSmart pricing in the $40s to high-end Lincoln Park boutiques and North Shore mobile services well above $150 for a medium dog."},
    {"name": "Indiana", "slug": "indiana", "abbr": "IN",
     "description": "Indiana's grooming industry is a study in solid Midwestern fundamentals: dependable independent salons in nearly every town of meaningful size, predictable seasonal cycles, and pricing that runs accessibly compared to coastal markets. Indianapolis and the surrounding Marion-Hamilton-Hendricks-Johnson county suburbs (Carmel, Fishers, Westfield, Greenwood, Plainfield) make up the largest market by far. Fort Wayne, South Bend, Evansville, Bloomington, Lafayette, and Terre Haute anchor the regional secondary markets, and northern Indiana's lake-country communities and southern Indiana's river towns each support clusters of independent groomers. The four-season climate creates a predictable grooming calendar. Spring is the heaviest deshedding season, with March through May packed for double-coated breeds — Goldens, Labs, Aussies, Bernese, German Shepherds. Summer humidity drives bath-and-blow demand and hot-spot prevention work. Fall brings tick checks for hunting dogs and trail-active pets, and winter brings the salt-on-paw care that all Midwestern groomers handle as a matter of routine. Indiana has a meaningful hunting-dog population — Beagles, English Setters, Labs, German Shorthaired Pointers — and several southern Indiana groomers specialize in post-field work during deer and small-game seasons. Pricing across Indiana is generally accessible, with most full-service grooms running $40–$70 for medium dogs. The Carmel-Fishers corridor north of Indianapolis runs higher, with several premium mobile services and boutique grooming studios; the Bloomington college-town market has a distinctive mix of premium and budget options. Mobile grooming has expanded steadily in the Indianapolis metro and the Fort Wayne area over the last several years."},
    {"name": "Iowa", "slug": "iowa", "abbr": "IA",
     "description": "Iowa's grooming culture leans heavily on long-standing relationships — most Iowa dog owners have a regular groomer they've used for years, and many salons here work primarily by repeat appointment with very little walk-in business. Des Moines and the Polk-Dallas-Warren county suburbs (West Des Moines, Urbandale, Ankeny, Waukee) make up the largest market. Cedar Rapids, Iowa City, the Quad Cities (Davenport, Bettendorf), Sioux City, Waterloo-Cedar Falls, Ames, and Dubuque round out the regional centers, and small-town Iowa is still served by an extensive network of single-operator salons, often run out of converted garages or attached to veterinary clinics. Iowa winters demand serious paw care — heavy salt and chemical de-icer use, ice ball formation in heavily-furred paws, and dry winter air that cracks pads. Most experienced Iowa groomers carry paw balm and sell take-home tubs, and sanitary trims for dogs that drag belly fur through slush are a standard winter add-on. Spring is the heaviest deshedding season, summer is bath-and-blow heavy, and fall brings tick checks and post-hunting-trip cleanups. Iowa has a substantial hunting-dog population — Labs, German Shorthaired Pointers, Beagles, Brittanys, English Setters — and many groomers handle post-field work as a routine service. Pricing across Iowa runs accessibly, with most full-service grooms in the $40–$70 range for medium dogs. The Des Moines metro and Iowa City college market run slightly higher than the statewide average. Mobile grooming has grown steadily but remains less common than in coastal states."},
    {"name": "Kansas", "slug": "kansas", "abbr": "KS",
     "description": "Kansas's grooming industry is split across two distinct market patterns: the Wichita and Kansas City suburban markets that look and price like neighboring metros, and the small-town and rural-community grooming networks across the plains, where a single experienced groomer often serves multiple counties. Wichita, Overland Park, Olathe, Lenexa, Topeka, Manhattan, Lawrence, and Salina anchor the larger metros. Hutchinson, Garden City, Dodge City, Pittsburg, and Hays serve the regional centers across western and southern Kansas. Climate considerations are dominated by wind, dust, and the temperature swings that define the Great Plains. Strong spring winds carry pollen, dust, and dry grass into coats; summer heat drives bath-and-blow services for cooling and tick removal; and Kansas winters bring the cold-and-salt combination that requires paw care for any dog walked on city sidewalks. Tornado season — late spring — sometimes shifts the grooming calendar in tornado-prone communities as appointments get rescheduled around weather events. Hunting and ranching dogs are a meaningful share of the rural Kansas grooming market: pheasant hunters bring in pointing breeds during late fall, and ranch dogs come in for periodic baths and tick checks rather than scheduled grooming. Family pets in the Wichita and Johnson County suburbs follow more standard cycles. Pricing across Kansas runs accessibly, with most full-service grooms in the $35–$70 range and the Johnson County suburbs running slightly higher in line with the broader Kansas City metro. Mobile grooming is expanding in metro Kansas City and Wichita."},
    {"name": "Kentucky", "slug": "kentucky", "abbr": "KY",
     "description": "Kentucky's grooming industry centers on three distinct markets: the Louisville metro and surrounding Jefferson and Oldham counties, the Lexington–Bluegrass region with its horse-country and university-town economy, and the Northern Kentucky cities (Florence, Independence, Erlanger, Covington) that function as part of the Greater Cincinnati metro. Bowling Green, Owensboro, Paducah, and the Eastern Kentucky communities along the Appalachian foothills add regional clusters. The Bluegrass region around Lexington has an unusually horse-and-dog-aware pet care culture: many of the state's most experienced groomers came up through the show-dog or hunting-dog circuits and bring breed-standard expertise to companion grooming work. Hunting dogs are a meaningful market share statewide — particularly Beagles, Walkers, Plotts, English Setters, and various coon-hunting breeds — and Eastern Kentucky groomers commonly handle post-hunt cleanups, including burr extraction and tick checks. The four-season climate with humid summers and moderately cold winters drives a predictable grooming calendar: heavy spring deshedding, summer hot-spot management, fall tick-check and post-trip work, and winter paw care for salt and slush in the urban areas. Pricing in Louisville and Lexington tracks regional Midwestern norms, with full-service grooms typically running $45–$85 for medium dogs. Northern Kentucky pricing aligns with Cincinnati's. Smaller-town Kentucky grooming runs more accessibly, often $35–$60. Mobile grooming has grown notably in the Louisville and Lexington metros and is expanding into the larger Bluegrass-region small towns where parking and travel time push some clients toward in-home service."},
    {"name": "Louisiana", "slug": "louisiana", "abbr": "LA",
     "description": "Louisiana's grooming industry is shaped by the most consistently hot and humid climate in the continental U.S., which creates year-round demand for coat care that's not strictly seasonal anywhere else in the country. New Orleans and the surrounding Jefferson and St. Tammany parishes anchor the largest market; Baton Rouge, Lafayette, Lake Charles, Shreveport-Bossier City, Monroe, and Houma round out the regional centers. The Acadiana region around Lafayette supports a distinctive Cajun-country pet culture with strong local groomer relationships and a meaningful share of hunting-dog clientele. Year-round subtropical humidity dominates Louisiana grooming work. Hot spots, yeast and bacterial skin issues, and ear infections from moisture trapped in floppy ears are routine concerns rather than seasonal ones. Most Louisiana groomers stock medicated shampoos as first-line products, offer flea-and-tick baths as standard add-ons, and handle ear cleanings with anti-fungal solutions on most appointments. Hurricane and flood seasons sometimes disrupt grooming schedules — especially after major storms when dogs need debris and contaminated-water rinses — and many Gulf Coast Louisiana groomers have flood-recovery experience. Hunting dogs come in heavily during and after duck season, and several Louisiana groomers specialize in retriever post-hunt work: full bath-and-blow, ear cleaning, gland expression, and tick checks. Pricing in New Orleans runs slightly above regional averages — a tourism-driven cost-of-living premium — while Baton Rouge, Lafayette, and Shreveport sit at standard regional rates. Smaller-town Louisiana grooming is generally accessible. Mobile grooming has grown in metro New Orleans and Baton Rouge, particularly post-Katrina as flooding concerns made some clients reluctant to leave dogs at salons."},
    {"name": "Maine", "slug": "maine", "abbr": "ME",
     "description": "Maine's grooming industry mirrors the state's geography — concentrated along the Portland-South Portland-Scarborough corridor, with secondary clusters in Lewiston-Auburn, Augusta, Bangor, and the coastal communities of Brunswick, Bath, and Camden, plus a network of small-town and mobile groomers serving the rural interior and Down East coastal communities. The winter climate is the dominant grooming consideration. Maine winters are long, cold, and snowy, and salt and chemical de-icers are used heavily on roads, sidewalks, and driveways. Most experienced Maine groomers handle paw rinses, paw balm applications, and sanitary trims for dogs that drag belly fur through slush as routine winter add-ons, and many sell paw balm and pet-safe ice melt to take home. Spring mud season — late March through April — is one of the busiest grooming periods of the year, with backed-up appointment books for several weeks as dogs that have been outside in mud, ice, and salt all winter need full bath-and-blow services to reset their coats. Maine has a substantial population of double-coated breeds — Labs, Newfoundlands, Bernese, Goldens, Australian Shepherds, plus working farm and homestead dogs — and undercoat raking and scheduled deshedding are routine services. Hunting dogs come in heavily in fall for post-bird-season cleanups. Pricing in Portland runs higher than the statewide average; smaller-town Maine grooming is generally accessible, with most full-service grooms in the $45–$80 range. Mobile grooming exists but is less common than in denser states, partly because rural drive times limit how many appointments mobile operators can complete in a day."},
    {"name": "Maryland", "slug": "maryland", "abbr": "MD",
     "description": "Maryland's grooming industry serves one of the densest dog-owning populations in the country, layered across a tight geography. The Washington DC suburbs in Montgomery and Prince George's counties — Bethesda, Rockville, Silver Spring, Gaithersburg, Bowie, and College Park — make up part of one of the highest-priced grooming markets nationally, with mobile services in particular pricing well into premium territory. Baltimore City and the surrounding suburbs (Towson, Pikesville, Catonsville, Columbia, Ellicott City) anchor the second major market. Annapolis and the Eastern Shore communities (Easton, Cambridge, Salisbury) serve the Chesapeake Bay-adjacent population. Western Maryland (Frederick, Hagerstown, Cumberland) operates at more accessible price points. Climate considerations follow mid-Atlantic patterns: humid summers driving hot-spot prevention and cooling cuts, cold-but-not-extreme winters with salt-on-paw care in urban areas, and clear spring and fall deshedding cycles. Maryland's Chesapeake Bay communities bring some specific demand — salt-water rinses for dogs that swim in the Bay, plus seasonal cleanup work for retrievers used in waterfowl hunting on the Eastern Shore. Pricing in Montgomery County and the closer-in DC suburbs runs significantly above the statewide average, with full-service grooms on medium dogs commonly $80–$150 at salons and well above that for mobile services. Baltimore-area pricing is more moderate. Mobile grooming is unusually well-developed across Maryland, particularly in Montgomery County and the Howard-Anne Arundel suburbs, where parking constraints and high household incomes make in-home service especially attractive."},
    {"name": "Massachusetts", "slug": "massachusetts", "abbr": "MA",
     "description": "Massachusetts's grooming industry is anchored by the Greater Boston metro and supported by strong secondary markets across the Commonwealth. Boston proper, Cambridge, Somerville, Brookline, and Newton make up a dense urban core where mobile grooming has flourished as an alternative to scarce parking and elevator-required apartment buildings. The Metro West (Framingham, Natick, Wellesley, Needham) and North Shore (Lynn, Salem, Beverly, Gloucester) and South Shore (Quincy, Braintree, Plymouth) suburbs add hundreds more salons and mobile operators. Worcester, Springfield, Lowell, and the Cape Cod and Pioneer Valley communities each anchor their own regional markets. Boston's grooming culture has a particularly strong emphasis on low-stress and anxiety-aware handling — many salons explicitly market gentle, force-free, or fear-free certifications, and several specialize in reactive or rescue dogs. Breed-specific grooming is well-developed too, with several boutique studios specializing in Poodles, Doodles, terrier hand-stripping, and show-quality breed cuts. New England's four seasons drive a clear grooming calendar. Spring deshedding is heavy after long winters; summer humidity drives hot-spot management and cooling-cut demand; fall brings tick checks, particularly for dogs that visit Cape Cod, the Berkshires, or the New Hampshire mountains; winter brings the salt-on-paw care that all Massachusetts groomers handle as a matter of routine. Pricing in Boston, Cambridge, and the wealthier western suburbs runs premium, with full-service grooms on medium dogs commonly $80–$160 at salons and higher for mobile. Worcester, Springfield, and outer-suburb pricing is more moderate."},
    {"name": "Michigan", "slug": "michigan", "abbr": "MI",
     "description": "Michigan's grooming industry is split between two distinct geographies: the densely-populated Lower Peninsula, particularly the Detroit-Ann Arbor-Lansing-Flint corridor and the western lakeshore communities anchored by Grand Rapids, Holland, and Kalamazoo, and the sparsely-populated Upper Peninsula, where small-town and mobile groomers cover wider service areas. Detroit and its suburbs (Royal Oak, Birmingham, Bloomfield Hills, Troy, Sterling Heights, Livonia, Dearborn) make up the largest market. Grand Rapids and the West Michigan corridor support the second major market with a particularly strong concentration of independent boutique salons. Traverse City, Petoskey, and the northern lower peninsula resort communities have developed a small but premium-priced grooming segment serving second-home owners. The Great Lakes climate creates several specific grooming considerations. Lake-effect snow keeps Michigan winters longer and snowier than equivalent latitudes elsewhere, which extends salt-on-paw care from November through April in many years. Spring deshedding for Michigan's substantial double-coated breed population — Goldens, Labs, Bernese, Aussies, German Shepherds, plus the Newfoundlands and Saint Bernards that are unusually well-represented in northern Michigan — runs heavy from late March through May. Summer brings lake swimming, which drives demand for post-swim rinses to clear out lake water and the algae or sand that comes with it. Pricing in Oakland County and the wealthier Detroit suburbs runs at the higher end of the regional range; Grand Rapids and Ann Arbor sit at standard regional rates; Upper Peninsula pricing is generally accessible."},
    {"name": "Minnesota", "slug": "minnesota", "abbr": "MN",
     "description": "Minnesota's grooming industry is one of the strongest in the Midwest, anchored by the Twin Cities metro — Minneapolis, St. Paul, Bloomington, Plymouth, Eagan, Edina, Minnetonka, Maple Grove — and supported by regional markets in Rochester, Duluth, St. Cloud, Mankato, and the lake-country communities of Brainerd, Alexandria, and Bemidji. The Twin Cities have an unusually deep boutique grooming scene with several breed-specialty studios, force-free certified salons, and a substantial mobile grooming presence in the suburbs. Extreme winters drive a more involved grooming calendar than nearly any other state. Subzero temperatures, lake-effect snow, and aggressive de-icer use mean paw care is a serious year-round concern from November through April. Many Minnesota groomers offer paw balm packages, sanitary trims for dogs that drag belly fur in slush, and trim-the-foot-feathers services that prevent ice ball formation in heavily-coated breeds. Spring deshedding is extraordinarily heavy here — Minnesota has one of the country's largest concentrations of double-coated breeds, including significant populations of Huskies, Malamutes, Bernese Mountain Dogs, Saint Bernards, Newfoundlands, Aussies, Goldens, and Labs — and most experienced groomers schedule month-of-March deshedding packages well in advance. Summer brings lake-swimming volume and the post-swim rinses that come with it. Pricing in the Twin Cities runs at the higher end of the Midwestern range, with full-service grooms on medium dogs commonly $60–$110 at salons. Greater Minnesota pricing is more accessible. Mobile grooming is well-developed in the metro and growing in regional markets."},
    {"name": "Mississippi", "slug": "mississippi", "abbr": "MS",
     "description": "Mississippi's grooming industry is shaped by a hot, humid Gulf-influenced climate that runs nearly year-round and a hunting-and-fishing pet culture that's deeply rooted in the state. Jackson and the surrounding Madison-Ridgeland-Brandon suburbs anchor the central Mississippi market. Hattiesburg, Tupelo, Meridian, Oxford, and Starkville serve regional markets, and the Mississippi Gulf Coast (Gulfport, Biloxi, Ocean Springs, Pascagoula) supports a coastal-community grooming cluster that handles everything from family pets to fishing-boat dogs that need salt-water rinses. Year-round subtropical humidity dominates the work. Hot spots, yeast issues, ear infections from moisture-trapped floppy ears, and bacterial skin issues are routine concerns rather than seasonal ones, and most experienced Mississippi groomers stock medicated shampoos and ear-cleaning solutions as first-line products. Flea and tick pressure is constant, especially in southern and coastal counties, and many groomers offer flea-and-tick baths as standard services rather than upcharges. Hunting dogs are a meaningful share of the rural Mississippi grooming market: Labradors, Beagles, Walkers, Plotts, and English Setters all come in heavily during and after fall and winter hunting seasons for post-field cleaning, burr extraction, and tick checks. Pricing across Mississippi runs at the lower end of the national range, with most full-service grooms in the $35–$60 range for medium dogs. The Gulf Coast and the Jackson metro run slightly higher than the statewide average. Mobile grooming exists but remains less common than in denser, wealthier markets."},
    {"name": "Missouri", "slug": "missouri", "abbr": "MO",
     "description": "Missouri's grooming industry is built around two large metros at opposite corners of the state — Kansas City and St. Louis — connected by smaller regional markets through the middle. The Kansas City metro on the western edge (Kansas City, Independence, Lee's Summit, Liberty, Blue Springs) and the St. Louis metro on the eastern edge (St. Louis, St. Charles, Chesterfield, O'Fallon, Wentzville) make up the bulk of the professional grooming infrastructure. Springfield, Columbia, Jefferson City, Joplin, Cape Girardeau, and the Lake of the Ozarks resort communities anchor the regional centers. Missouri's variable climate creates a four-season grooming cycle. Summers are hot and humid, especially in southern and southeastern Missouri, driving heat-management work and hot-spot prevention. Winters are cold but not extreme outside of unusual cold snaps, with salt-on-paw care for urban and suburban dogs. Spring brings heavy deshedding for the state's substantial double-coated breed population, and fall brings the tick checks and post-trip cleanups for the hunting and outdoor-active dogs that are common across rural Missouri. The Lake of the Ozarks region drives summer-season demand for water-dog post-swim services. Pricing in St. Louis and Kansas City runs at standard regional rates — full-service grooms commonly $50–$90 for medium dogs at metro salons — with the wealthier St. Louis suburbs (Ladue, Clayton, Town and Country) and the JoCo-side Kansas City suburbs running slightly above. Springfield, Columbia, and outstate Missouri pricing is more accessible. Mobile grooming is well-established in both metros."},
    {"name": "Montana", "slug": "montana", "abbr": "MT",
     "description": "Montana's grooming industry is small relative to its geography but serves a demanding clientele. Working dogs are a substantial share of the state's pet population — ranching dogs, hunting dogs, sled dogs, search-and-rescue dogs, plus family pets that spend most of their lives outdoors — and grooming work here often skews toward functional services rather than show-style cuts. Billings, Missoula, Bozeman, Great Falls, Helena, Kalispell, and Butte anchor the largest markets. The Flathead Valley, Bitterroot Valley, and Paradise Valley each support regional grooming clusters that serve both year-round residents and the growing population of remote workers and second-home owners who have relocated to Montana over the past several years. Climate considerations are dominated by extremes. Summers are hot and dry, drawing demand for cooling cuts and dust-removal baths after trail trips. Winters are long, cold, and snowy, with the salt-on-paw care that comes with city sidewalks plus the more specific concerns of dogs that work in snow, mud, and ice for extended periods. Spring brings heavy deshedding for Montana's substantial population of double-coated breeds — Aussies, Border Collies, Goldens, Labs, plus the working-line German Shepherds and Anatolian Shepherds that are common on ranches. Burr and seed-pod extraction is a routine service, particularly in late summer and fall when foxtails and grass awns are at peak risk. Pricing in Bozeman runs notably premium, reflecting the wealthy second-home market; Billings, Missoula, and Great Falls sit at standard regional rates. Mobile grooming is well-developed in the Bozeman and Missoula areas in particular."},
    {"name": "Nebraska", "slug": "nebraska", "abbr": "NE",
     "description": "Nebraska's grooming industry centers on Omaha and Lincoln, the state's two largest metros, with smaller regional markets in Grand Island, Kearney, Norfolk, Columbus, Hastings, North Platte, and Scottsbluff. The Omaha metro (Omaha, Bellevue, Papillion, La Vista, Council Bluffs across the Missouri River in Iowa) is by far the largest, with a strong network of independent salons, several boutique studios in midtown and west Omaha, and a growing mobile grooming presence in the western suburbs. Lincoln's grooming scene reflects its university-town and state-capital character, with a mix of family-pet salons and a few specialty operations. The Great Plains climate creates a clear seasonal grooming cycle. Strong year-round winds carry pollen, dust, and seed-pods into coats; summer heat drives bath-and-blow services for cooling and tick removal; and Nebraska winters bring the cold-and-salt combination that requires paw care for any dog walked on city sidewalks. Spring is the heaviest deshedding season for the state's substantial population of double-coated breeds. Hunting dogs are a meaningful share of the rural Nebraska grooming market — pheasant and quail hunters bring in pointing breeds during fall and early winter for post-field cleanup, and many small-town groomers handle this work as a routine seasonal service. Pricing in Omaha runs slightly above the statewide average, with most full-service grooms in the $45–$80 range for medium dogs at metro salons. Lincoln and outstate pricing is more accessible. Mobile grooming has grown notably in the Omaha metro over the past several years."},
    {"name": "Nevada", "slug": "nevada", "abbr": "NV",
     "description": "Nevada's grooming industry is concentrated in two distinct markets: the Las Vegas-Henderson-North Las Vegas metropolitan area in the south, and the Reno-Sparks-Carson City corridor in the north, with smaller markets in Elko and the rural communities along the I-80 corridor. The two metros operate in genuinely different climates — Las Vegas with extreme low-desert summer heat and mild winters, Reno with high-desert seasons including real winters with snow and freezing temperatures — and their grooming patterns reflect that. In Las Vegas, summer heat is the dominant grooming consideration. Pavement temperatures reach 160°F+ in July and August, and paw pad protection, paw rinses, and protective wax treatments are routine year-round add-ons. Cooling cuts are common but selective — reputable groomers refuse to shave double-coated breeds, since the undercoat protects from heat as much as cold. Dry-air skin issues, allergy season pollens, and the static and dandruff that come with low desert humidity drive demand for moisturizing shampoos and leave-in conditioners. Reno's grooming work follows more of a four-season pattern, with winter paw care for salt and snow on Sierra-adjacent communities, spring deshedding, and summer pollen and allergy work. Pricing in the Las Vegas Strip-adjacent neighborhoods (Summerlin, Henderson, Anthem) runs at the higher end of the regional range, with mobile services in particular pricing premium. North Las Vegas and Reno are more moderate. Mobile grooming is unusually popular in Las Vegas — partly a function of the heat (clients don't want to walk dogs from car to salon), partly the developed mobile-service infrastructure across the metro."},
    {"name": "New Hampshire", "slug": "new-hampshire", "abbr": "NH",
     "description": "New Hampshire's grooming industry is distributed across the state's small but distinct regions: the Manchester-Nashua-Concord population corridor in the south, the Seacoast communities of Portsmouth, Dover, and Exeter, the Lakes Region around Lake Winnipesaukee, the Monadnock Region in the southwest, and the White Mountains and Great North Woods communities serving the ski-and-trail tourism economy. The state's outdoor culture drives a meaningful portion of grooming demand. White Mountains and Lakes Region dogs spend significant time on trails and in lakes during summer and fall, which translates into demand for full bath-and-blow cleanups for burrs, brush debris, and lake water; tick checks during peak tick months (May through September); and post-trip paw inspections for cuts and thorns. Winter brings serious cold and snow, with salt and chemical de-icers used heavily on town roads and sidewalks. Most experienced New Hampshire groomers handle paw rinses, paw balm applications, and trim-the-foot-feathers services for ice ball prevention as routine winter add-ons. Spring mud season — late March through April — is one of the year's busiest grooming periods, with backed-up appointment books as dogs that have been outside in mud and slush all winter need full bath-and-blow services to reset their coats. Pricing in the Seacoast and the wealthier Lakes Region communities runs notably premium, with mobile services in particular pricing high; Manchester, Nashua, and the central state run at standard regional rates. Mobile grooming is unusually well-developed for a small state, particularly in the Seacoast and the Manchester-Nashua corridor."},
    {"name": "New Jersey", "slug": "new-jersey", "abbr": "NJ",
     "description": "New Jersey has one of the densest grooming markets in the country, packed into a small geography. North Jersey — Bergen, Hudson, Essex, Passaic, Union, and Morris counties — operates effectively as part of the Greater New York metro and shares its premium pricing patterns. Central Jersey (Middlesex, Somerset, Mercer, Monmouth) and the Princeton-Trenton corridor support strong suburban grooming markets. South Jersey — Camden, Burlington, Gloucester, Atlantic, Cape May, Ocean — leans toward the Greater Philadelphia region but with its own distinctive Shore community grooming patterns. The Jersey Shore generates a meaningful summer demand spike, particularly in Cape May County, the Wildwoods, Long Beach Island, and the Asbury Park-Belmar corridor: vacation-home owners with dogs book appointments after beach days for sand removal, salt-water rinses, and the seasonal flea pressure that comes with dunes and beach grass. North Jersey's grooming culture has a particularly strong emphasis on mobile services, partly because parking and access constraints in dense suburban neighborhoods push owners toward in-home appointments, and partly because high household incomes support premium pricing. Several North Jersey mobile operators run waitlists rather than open booking. Pricing in Bergen County, the wealthier Morris County towns, and the Princeton corridor runs premium — full-service grooms on medium dogs commonly $80–$160 at salons and substantially higher for mobile. South Jersey and outer counties operate at more accessible rates aligned with Greater Philadelphia. The four-season climate, salt-on-paw winters, and humid summers drive a predictable grooming calendar across the state."},
    {"name": "New Mexico", "slug": "new-mexico", "abbr": "NM",
     "description": "New Mexico's grooming industry is shaped by altitude, dry air, and a cultural mix that's reflected in the state's pet population. Albuquerque, Rio Rancho, Santa Fe, Las Cruces, Roswell, Farmington, and the Los Alamos-Espanola corridor anchor the regional markets. Smaller communities across the state — from Taos and Silver City to Carlsbad and Clovis — are typically served by a single experienced groomer or a mobile operator covering wider service areas. High-altitude dry air drives most of the state's distinctive grooming work. Static, dandruff, dry-skin flaking, and the chronic itching that comes with sustained low humidity are common concerns, and most New Mexico groomers carry humectant conditioners, oat-based moisturizers, and leave-in coat oils as standard products. UV exposure is intense across the state and year-round at Santa Fe and Los Alamos elevations, so summer cuts on light-skinned breeds (white Shepherds, Pit-mix breeds, dogs with pink ears or thin head fur) typically leave more protective coat than they would at sea level. Tick exposure in juniper and pinyon country drives demand for tick checks during spring and fall. Foxtails and seed pods are a constant threat in late summer, and many New Mexico groomers handle paw and ear extractions as routine appointments. Pricing across New Mexico runs at the lower-to-mid range of the national distribution, with most full-service grooms in the $40–$75 range for medium dogs. Santa Fe and Los Alamos run notably higher than the rest of the state, reflecting the wealthier resident base. Mobile grooming has expanded steadily in the Albuquerque metro."},
    {"name": "New York", "slug": "new-york", "abbr": "NY",
     "description": "New York State's grooming industry is one of the largest and most diverse in the country, with operating models that span every imaginable price point and service style. New York City alone — Manhattan, Brooklyn, Queens, the Bronx, Staten Island — supports thousands of grooming businesses, from $200+ Upper East Side and Tribeca boutiques where appointments are scheduled like spa treatments, to mid-tier Brooklyn neighborhood salons, to budget-friendly outer-borough chains. Mobile grooming has become exceptionally well-developed in the city, particularly in Manhattan and brownstone Brooklyn, where parking constraints and elevator-required apartment buildings make traveling to a salon difficult. Long Island (Nassau and Suffolk counties) runs as a distinct premium-priced market, with strong concentrations in the North Shore communities (Manhasset, Garden City, Roslyn, Huntington) and the Hamptons during summer. Westchester County and the Hudson Valley follow similar premium suburban patterns, with secondary clusters in Yonkers, White Plains, and the river-towns north along the Hudson. Upstate New York is its own ecosystem. The Buffalo-Niagara metro has a deep family-pet grooming community shaped by lake-effect snow and harsh winters. Rochester, Syracuse, Albany, Utica, Binghamton, and the Finger Lakes communities each anchor regional clusters. The Adirondacks, Catskills, and the Southern Tier have smaller markets served by local independents and traveling mobile groomers. Climate considerations vary by region. NYC and Long Island handle salt-on-paw winters and humid summers; Upstate handles harsher winters and shorter summers; the Adirondacks add the post-trail and tick-check work characteristic of mountain-and-trail communities."},
    {"name": "North Carolina", "slug": "north-carolina", "abbr": "NC",
     "description": "North Carolina has one of the fastest-growing grooming markets in the South, tracking the population boom that's reshaped the state over the past decade. The Charlotte metro (Charlotte, Concord, Huntersville, Matthews, Mooresville) is the largest single market, with the Research Triangle (Raleigh, Durham, Cary, Chapel Hill, Apex, Wake Forest) close behind and supporting an unusually deep concentration of premium and boutique grooming services. The Triad (Greensboro, Winston-Salem, High Point) anchors a third major market, and Wilmington, Asheville, Fayetteville, Hickory, and the Outer Banks round out the regional centers. Climate is split across the state's three geographic zones. The coastal plain has hot, humid summers driving hot-spot management and flea-and-tick work; the Piedmont has the four-season cycle most groomers across the South handle as a matter of routine; and the Western North Carolina mountains around Asheville have shorter summers, real winters, and the post-trail work characteristic of mountain communities. Asheville's grooming culture is distinctive — heavily artisan, with several boutique studios specializing in breed-standard cuts, force-free certifications, and eco-conscious products that mirror the city's broader retail character. Pricing in Charlotte and the Triangle runs at standard regional rates with notable premium pockets (SouthPark in Charlotte, North Hills in Raleigh, downtown Durham) where mobile and boutique services price well above the metro average. The Outer Banks see strong summer-season demand from vacation-home owners. Mobile grooming has expanded rapidly in Charlotte, the Triangle, and Asheville over the past several years."},
    {"name": "North Dakota", "slug": "north-dakota", "abbr": "ND",
     "description": "North Dakota's grooming industry is small but reliable, serving a state where harsh winters, working-dog populations, and a strong culture of long-term groomer-client relationships shape the market. Fargo (along with Moorhead just across the Red River in Minnesota) is the largest metro, with Bismarck-Mandan as the second major market. Grand Forks, Minot, Williston, Dickinson, and Jamestown anchor regional centers, and the western oil-patch communities have seen meaningful population growth and corresponding pet-care expansion over the past decade. Extreme winters drive a substantial portion of the grooming calendar. Subzero temperatures, prolonged snow cover, ground-blizzard conditions, and aggressive de-icer use make winter paw care especially important, and most experienced North Dakota groomers handle paw rinses, paw balm applications, and trim-the-foot-feathers services as routine winter work. Spring deshedding for the state's substantial population of double-coated working breeds — Labs, Goldens, Aussies, German Shepherds, Huskies, and the various ranching and hunting dogs that are common across rural North Dakota — runs heavy in March and April. Summer brings post-trip cleanups for hunting and trail dogs, particularly in the Red River Valley and the Badlands. Fall pheasant hunting drives demand for post-field work on pointing breeds. Pricing across North Dakota runs accessibly, with most full-service grooms in the $35–$70 range for medium dogs. Fargo and the wealthier Bismarck neighborhoods run slightly higher than the statewide average. Mobile grooming has grown in the Fargo-Moorhead area but remains less common in the rest of the state."},
    {"name": "Ohio", "slug": "ohio", "abbr": "OH",
     "description": "Ohio's grooming industry is unusually deep and well-distributed for a single state, anchored by four major metros that each support distinct grooming cultures. Columbus and the surrounding Franklin-Delaware-Fairfield county suburbs (Dublin, Westerville, Worthington, Powell, Hilliard) make up the largest market and have seen significant growth in boutique and mobile grooming over the past several years. Cleveland and the surrounding suburbs (Lakewood, Westlake, Beachwood, Solon, Strongsville) anchor a strong family-pet grooming market shaped by lake-effect snow and the harsh winters that come with proximity to Lake Erie. Cincinnati and its Northern Kentucky-adjacent suburbs (West Chester, Mason, Loveland, Blue Ash) operate as a single metro grooming market with regional southwestern Ohio character. Dayton, Akron, Toledo, Youngstown, and the smaller cities and college towns (Athens, Bowling Green, Oxford) round out the regional centers. Lake-effect snow shapes Northeast Ohio grooming significantly. Cleveland and the snow-belt counties east see noticeably heavier and longer winters than the rest of the state, with extended salt-on-paw care from November through March in many years. The four-season climate elsewhere drives a predictable cycle: heavy spring deshedding, summer hot-spot management and humidity work, fall tick checks for trail-active dogs, winter paw care. Pricing across Ohio's major metros runs at standard Midwestern regional rates, with full-service grooms commonly $50–$90 for medium dogs at metro salons. Boutique and mobile services in the wealthier Columbus and Cleveland suburbs run notably higher. Mobile grooming is well-developed in all three of the major metros."},
    {"name": "Oklahoma", "slug": "oklahoma", "abbr": "OK",
     "description": "Oklahoma's grooming industry serves a state with a strong working-dog and hunting-dog culture layered over the urban family-pet markets of Oklahoma City and Tulsa. The OKC metro (Oklahoma City, Edmond, Norman, Moore, Yukon, Mustang) is the largest market by population, with Tulsa and its suburbs (Broken Arrow, Owasso, Bixby, Jenks) as the second major market. Lawton, Stillwater, Enid, Muskogee, Ardmore, and Bartlesville anchor regional centers, and the rural communities across western and southeastern Oklahoma are typically served by long-tenured independent groomers and a growing mobile-grooming network. Climate considerations are dominated by heat, humidity, and weather extremes. Oklahoma summers are hot and humid, driving cooling-cut demand and hot-spot prevention work. Tornado season — peak in late spring — sometimes disrupts the grooming calendar around major weather events. Wind is a constant factor, kicking up dust, pollen, and seed pods that work into coats. Hunting dogs are a meaningful share of the rural Oklahoma grooming market: quail, pheasant, dove, and waterfowl hunters bring in pointing breeds and retrievers heavily during fall and winter for post-field cleanup, burr extraction, tick checks, and ear cleaning. Several Oklahoma groomers also handle livestock-guardian dogs (Anatolian Shepherds, Great Pyrenees) common on rural properties. Pricing across Oklahoma runs accessibly compared to coastal markets, with most full-service grooms in the $40–$70 range for medium dogs. The Edmond and Tulsa midtown/Brookside markets run slightly higher, with several boutique studios and mobile services pushing into premium territory."},
    {"name": "Oregon", "slug": "oregon", "abbr": "OR",
     "description": "Oregon's grooming industry is shaped by a sharp climate split — the wet, mild Pacific Northwest west of the Cascades and the dry, sunny high desert east of the mountains — and by Portland's distinctively pet-forward urban culture. The Portland metro (Portland, Beaverton, Hillsboro, Tigard, Lake Oswego, Gresham, Vancouver across the Columbia in Washington) is the largest market by far, with one of the country's deepest concentrations of force-free certified salons, breed-specialty studios, and mobile grooming operators. Salem, Eugene, Corvallis, and the Willamette Valley anchor Western Oregon's secondary markets. Bend, Redmond, and the Central Oregon high-desert communities serve the eastern side, with smaller regional clusters in Medford-Ashland, the Oregon Coast (Newport, Florence, Coos Bay), and the Columbia Gorge. West-of-Cascades grooming work is dominated by moisture management. Constant rain from October through May drives demand for thorough drying after baths, anti-mildew shampoos for dogs that walk daily in wet weather, and the kind of bath frequency that East Coast or Southern dogs would find excessive. Pacific Northwest dogs get muddy, and they get muddy often, and Portland-area groomers handle the rinses, blow-outs, and coat-resets that come with that. East-of-Cascades grooming work follows a more standard high-desert pattern, with dry-skin care and UV protection more prominent than moisture management. Pricing in Portland runs at the higher end of the regional range, with several boutique studios and mobile services pricing well above $100 for medium dogs. Salem, Eugene, and Bend operate at more moderate rates."},
    {"name": "Pennsylvania", "slug": "pennsylvania", "abbr": "PA",
     "description": "Pennsylvania's grooming industry stretches across two large metros at opposite ends of the state and a network of small-city, college-town, and rural-community groomers in between. Philadelphia and the surrounding Bucks, Montgomery, Chester, and Delaware county suburbs (Doylestown, Media, King of Prussia, West Chester, Newtown) make up the largest market and operate as part of the broader Greater Philadelphia metro. Pittsburgh and the surrounding Allegheny County communities (Mt. Lebanon, Cranberry Township, Wexford, Monroeville, Bethel Park) anchor Western Pennsylvania. Harrisburg, Lancaster, York, Reading, Allentown, Bethlehem, Scranton, Wilkes-Barre, Erie, and the State College university market each support regional centers. Lancaster County has a distinctive grooming community shaped by the area's significant Amish and Mennonite populations and the breed-specific work that comes with farm dogs and the licensed dog breeders concentrated in that part of the state. Pittsburgh's grooming culture has a strong neighborhood-shop character, with an unusually high share of independent salons that have served the same neighborhoods for decades. The four-season climate drives a predictable grooming calendar, with Western Pennsylvania getting heavier and longer winters than Philadelphia. Pricing in Center City Philadelphia and the Main Line suburbs runs premium, with full-service grooms commonly $80–$140 for medium dogs at salons and substantially higher for mobile services. Pittsburgh, Harrisburg, and the smaller cities operate at more moderate rates. Mobile grooming is well-developed in both major metros, particularly in the Philadelphia suburbs where parking and travel time push some clients toward in-home appointments."},
    {"name": "Rhode Island", "slug": "rhode-island", "abbr": "RI",
     "description": "Rhode Island is the smallest state in the country, but its grooming market punches above its weight thanks to a high pet ownership rate, dense population, and a culture that takes pet care seriously. Providence, Cranston, Warwick, and Pawtucket make up the urban core. Newport and the East Bay communities (Bristol, Barrington, Tiverton) support a wealthier, premium-priced grooming segment shaped by the historic homes and second-home owners that define the area. South County (Westerly, Narragansett, Wakefield, Charlestown) has its own distinct beach-community pattern with summer demand spikes. Northern Rhode Island (Woonsocket, Cumberland, Smithfield) operates at more accessible price points. The coastal New England climate brings four real seasons but moderated by Atlantic proximity. Spring and fall are the heaviest deshedding seasons; humid summers drive hot-spot management; winters bring salt-on-paw care similar to Massachusetts and Connecticut. Newport in particular sees a meaningful summer demand spike from second-home owners and yacht-community pet care: salt-water rinses, sand removal, and the kind of premium-priced mobile services that tourist economies sustain. Tick exposure is significant during peak months and many groomers handle tick checks as a routine summer add-on. Mobile grooming has become unusually well-developed across Rhode Island for a state of its size — the dense suburban geography keeps drive times manageable, and many residents prefer in-home service. Pricing in Newport, the East Bay, and downtown Providence runs at the higher end of the regional range. Cranston, Warwick, and inland communities operate at more moderate rates aligned with broader New England norms."},
    {"name": "South Carolina", "slug": "south-carolina", "abbr": "SC",
     "description": "South Carolina's grooming industry has expanded substantially over the past decade, tracking the state's significant population growth and the influx of retirees and remote workers along the coast. Charleston and the surrounding Mt. Pleasant, North Charleston, and Summerville communities make up the largest market, with the Myrtle Beach-Conway-Pawleys Island corridor as the second major coastal market. The Greenville-Spartanburg-Anderson upstate metro anchors the northwestern part of the state with an unusually deep family-pet grooming community shaped by the region's manufacturing and tech-corridor growth. Columbia and Hilton Head/Bluffton round out the regional centers. Year-round subtropical humidity dominates South Carolina grooming work, especially along the coast. Hot-spot management, anti-fungal ear cleaning, hot-spot prevention shampoos, and flea-and-tick baths are routine year-round services rather than seasonal upcharges. Charleston's tropical-storm and hurricane season sometimes disrupts the grooming calendar; many coastal groomers have post-storm cleanup experience, including salt-water rinses and contaminated-water decontamination. Hilton Head and the Lowcountry have a particularly strong premium grooming segment shaped by the resort and second-home economy. Hunting dogs are a meaningful share of the upstate and Pee Dee region grooming market. Pricing in Charleston's historic-district and Mt. Pleasant neighborhoods runs at the higher end of the regional range, with mobile services in particular pricing premium. Greenville and Columbia operate at standard regional rates. Smaller-town and rural South Carolina pricing is generally accessible. Mobile grooming has expanded rapidly in Charleston and the upstate over the past several years."},
    {"name": "South Dakota", "slug": "south-dakota", "abbr": "SD",
     "description": "South Dakota's grooming industry is divided across two distinct geographies: Sioux Falls and the eastern South Dakota communities oriented toward the Minnesota and Iowa borders, and the western South Dakota communities anchored by Rapid City and the Black Hills region with their distinct outdoor-recreation and tourism-driven economy. Sioux Falls is by far the largest market and has seen meaningful growth over the past decade, with several boutique studios and a developing mobile grooming presence. Rapid City, Spearfish, and the Black Hills resort communities (Deadwood, Custer, Hill City) support a smaller but distinctive grooming community shaped by tourism and the state's substantial outdoor and hunting culture. Aberdeen, Pierre, Mitchell, Brookings, Watertown, and Yankton round out the regional centers. Climate considerations are dominated by extremes. South Dakota winters are long, cold, and snowy with strong wind chills and aggressive de-icer use in the metros. Spring brings heavy deshedding for the state's substantial population of double-coated working breeds. Summers are hot and dry on the western side and hot and humid on the eastern side, both driving cooling-cut demand and bath-and-blow services. The Black Hills region has a year-round outdoor culture with hunting, hiking, and trail-active dogs that need post-trip burr extraction, paw checks, and tick removal. Pheasant hunting season — late October through January — drives a noticeable spike in grooming demand for pointing breeds and Labradors. Pricing across South Dakota runs accessibly, with most full-service grooms in the $35–$70 range for medium dogs. Sioux Falls runs slightly higher than the statewide average."},
    {"name": "Tennessee", "slug": "tennessee", "abbr": "TN",
     "description": "Tennessee's grooming industry is anchored by four distinctly characterful metros: Nashville with its rapid growth and pet-forward culture, Memphis with its deep neighborhood-shop tradition, Knoxville's mountain-adjacent and university-driven market, and Chattanooga's outdoor-and-river-recreation pet scene. Each operates with its own pricing patterns and service mix. Nashville and the surrounding Williamson County suburbs (Franklin, Brentwood, Nolensville, Spring Hill) have seen explosive grooming-industry growth over the past decade. Several boutique studios and high-end mobile services now price well above regional averages, and the Nashville-Brentwood corridor in particular has become one of the South's premium grooming markets. Memphis maintains a strong neighborhood-salon tradition with deep groomer-client relationships and pricing more accessible than Nashville. Knoxville and Chattanooga sit at standard regional rates with growing premium segments tied to their Smoky Mountains-adjacent and Tennessee River-adjacent outdoor cultures. The four-season climate with hot, humid summers and moderate winters drives a predictable grooming calendar. East Tennessee's mountain communities add post-trail and tick-check work characteristic of trail-active dogs. Hunting dogs — Walker Coonhounds, Treeing Walker Coonhounds, Plotts (the state dog), Labradors, Beagles — are a meaningful share of the rural Tennessee grooming market. Several Eastern and Middle Tennessee groomers specialize in coon and bird-hunting dog post-field work. Pricing across Tennessee runs at the lower-to-mid range of the national distribution outside the Nashville-Brentwood corridor. Mobile grooming has expanded rapidly in the Nashville metro and is growing in Knoxville and Chattanooga."},
    {"name": "Texas", "slug": "texas", "abbr": "TX",
     "description": "Texas has one of the largest dog-grooming markets in the country, spread across genuinely distinct regional climates and metro cultures. Houston and the surrounding Harris-Fort Bend-Montgomery county suburbs (Sugar Land, The Woodlands, Katy, Cypress, Pearland) make up the largest single market, shaped by Gulf Coast humidity and intense summer heat. The Dallas-Fort Worth Metroplex (Dallas, Fort Worth, Plano, Frisco, Arlington, Irving, Garland, McKinney) is close behind and operates with North Texas climate patterns — hot summers, real winters with occasional ice storms, and the four-season cycle. Austin's grooming scene has its own pet-forward, Travis County character with several breed-specialty studios and a substantial mobile-grooming presence. San Antonio anchors South Central Texas. El Paso operates with West Texas/Chihuahuan Desert climate considerations. Houston, Corpus Christi, and the broader Texas Gulf Coast deal with year-round subtropical humidity, hurricane season, and the kind of hot-spot prevention work that humid climates demand. Pavement temperatures in Texas summer are extreme, and paw pad protection is a routine concern. Most Texas groomers will offer cooling cuts but refuse to shave double-coated breeds — the undercoat protects from heat as much as cold. Tick exposure is significant in the Hill Country and East Texas, and many groomers handle tick checks as a standard service. Pricing varies dramatically across the state, from the moderate rates of San Antonio neighborhoods to the premium pricing of Highland Park (Dallas), Memorial (Houston), and West Lake Hills (Austin). Mobile grooming is exceptionally well-developed across all the major Texas metros."},
    {"name": "Utah", "slug": "utah", "abbr": "UT",
     "description": "Utah's grooming industry is concentrated along the Wasatch Front, with Salt Lake City, Sandy, West Jordan, South Jordan, Draper, Lehi, Provo, Orem, and Ogden anchoring the largest population center. Park City's resort economy and St. George's Southern Utah retiree-and-second-home market each support smaller but distinct premium-priced grooming segments. Logan in Cache Valley and Cedar City and Moab in the southern part of the state add regional clusters. Utah's outdoor culture drives a meaningful share of grooming demand. Wasatch Front dogs are unusually trail-active — the proximity of Mill Creek Canyon, Big and Little Cottonwood Canyons, and the Wasatch ridgeline trails means many family pets see real backcountry use, which translates into demand for post-trail bath-and-blow services, burr extraction, paw inspections, and tick checks. The Park City and Deer Valley resort communities add a winter-recreation dimension: dogs that ski-tour, snowshoe, or run in deep snow need ice-ball prevention work and paw care, plus the post-trip rinses that come with a snow-recreation lifestyle. Climate considerations split between high-desert dryness (Salt Lake, Provo, St. George) and mountain-recreation conditions (Park City, Logan). Dry-air skin issues are common; static, dandruff, and flaking drive demand for moisturizing shampoos and leave-in conditioners. Pricing in Park City runs notably premium, with mobile and boutique services aligned with other ski-town economies. Salt Lake City and the Wasatch Front sit at standard regional rates. St. George operates similarly. Mobile grooming has expanded steadily in the Salt Lake metro over the past several years."},
    {"name": "Vermont", "slug": "vermont", "abbr": "VT",
     "description": "Vermont has a small but distinctive grooming industry that reflects the state's rural character and outdoor culture. Burlington and the Chittenden County suburbs (South Burlington, Essex, Williston, Colchester) make up the largest market by far. Montpelier, Barre, Rutland, Bennington, Brattleboro, and St. Johnsbury anchor regional centers, and small-town and mobile groomers cover the rest of the state, where service areas can stretch across multiple towns. The ski-and-resort communities of Stowe, Manchester, Killington, and Stratton support a small premium-priced grooming segment shaped by second-home owners. Vermont winters are cold, snowy, and long. Salt and chemical de-icers are used heavily on town and state roads, and most experienced Vermont groomers handle paw rinses, paw balm applications, and trim-the-foot-feathers services for ice ball prevention as routine winter add-ons. Spring mud season — the legendary Vermont mud season that runs roughly from late March through late April — is one of the year's busiest grooming periods, with backed-up appointment books for several weeks as dogs that have been outside in mud and slush all winter need full bath-and-blow services to reset their coats. The state's substantial population of double-coated breeds — Goldens, Labs, Bernese, Aussies, plus the Newfoundlands and Saint Bernards that are unusually well-represented in rural Vermont — drive heavy spring deshedding demand. Tick exposure is significant May through September. Pricing in Burlington and the resort towns runs at the higher end of the regional range; smaller-town Vermont grooming is generally accessible. Mobile grooming exists but is limited by the rural geography."},
    {"name": "Virginia", "slug": "virginia", "abbr": "VA",
     "description": "Virginia's grooming industry reflects the state's geographic and economic split between Northern Virginia's DC-suburb wealth, the Richmond capital region, and the diverse Hampton Roads, Shenandoah Valley, and Southwest Virginia communities further from the metro corridors. Northern Virginia (Arlington, Alexandria, Fairfax, Loudoun, Prince William counties — including Reston, Vienna, McLean, Tysons, Ashburn, Leesburg, Manassas, Woodbridge) operates as part of the Greater Washington DC metro and shares its premium pricing patterns. Richmond and the surrounding Henrico-Chesterfield-Hanover suburbs anchor Central Virginia. Hampton Roads (Virginia Beach, Norfolk, Chesapeake, Newport News, Hampton, Portsmouth, Suffolk) supports a coastal-and-military-base grooming community with a meaningful share of military-family clients who book grooming around deployment and PCS schedules. Charlottesville, Roanoke, Lynchburg, Harrisonburg, Winchester, and Fredericksburg round out the regional centers. Climate considerations follow mid-Atlantic patterns with regional variation. Northern Virginia and Tidewater have humid summers driving hot-spot prevention and cooling-cut demand; the Shenandoah Valley and Southwest Virginia's Blue Ridge communities have shorter, milder summers and the post-trail tick-and-burr work characteristic of mountain communities. Virginia Beach in particular adds salt-water rinses for dogs that swim in the Atlantic, plus seasonal flea pressure from beach grass and dunes. Pricing in Northern Virginia runs at the higher end of the regional range, with full-service grooms commonly $80–$160 for medium dogs at salons and substantially higher for mobile services. Richmond and Hampton Roads operate at standard regional rates. Smaller-town Virginia grooming is generally accessible. Mobile grooming is unusually well-developed in NoVa."},
    {"name": "Washington", "slug": "washington", "abbr": "WA",
     "description": "Washington's grooming industry is split sharply across the Cascades. The wet, mild Western Washington corridor — Seattle, Tacoma, Bellevue, Redmond, Kirkland, Everett, Olympia, Bellingham, plus the Olympic Peninsula and Whidbey Island communities — operates in genuinely different conditions than the dry, sunny Eastern Washington side anchored by Spokane, the Tri-Cities (Kennewick, Pasco, Richland), Yakima, Wenatchee, and the Walla Walla wine country. Western Washington's grooming culture is one of the most pet-forward in the country. Seattle has an exceptional concentration of force-free certified salons, breed-specialty studios, and mobile grooming operators, and the Eastside (Bellevue, Redmond, Sammamish, Issaquah) supports a particularly deep premium-priced segment driven by tech-industry household incomes. Constant rain from October through May drives demand for thorough drying after baths, anti-mildew shampoos for dogs that walk daily in wet weather, and frequent bath cycles that East Coast or Southern dogs would find excessive. Pacific Northwest dogs get muddy and they get muddy often. Eastern Washington follows a more standard four-season pattern: hot, dry summers driving cooling-cut demand and pollen-related skin work; cold winters with snow and de-icer paw care; spring and fall deshedding cycles. Spokane's grooming community has an unusually neighborhood-shop character with strong long-term groomer-client relationships. Pricing in Seattle proper, the Eastside, and Bainbridge Island runs at the higher end of the national range. Tacoma, Olympia, and the rest of Western Washington operate at standard regional rates. Spokane and Eastern Washington pricing is more accessible. Mobile grooming is exceptionally well-developed in the Seattle metro."},
    {"name": "West Virginia", "slug": "west-virginia", "abbr": "WV",
     "description": "West Virginia's grooming industry serves a small, geographically dispersed population in a state defined almost entirely by Appalachian terrain. Charleston, Huntington, and the Kanawha Valley anchor the largest market. Morgantown's university-driven economy supports a distinct grooming community in the north-central part of the state. The Eastern Panhandle (Martinsburg, Charles Town, Harpers Ferry) operates as part of the broader Washington DC commuter belt. Wheeling, Parkersburg, Beckley, Clarksburg, and Fairmont serve regional centers, and many of the state's smaller communities are served by long-tenured independent groomers or mobile operators covering wider service areas. Hunting dogs are a significant share of the West Virginia grooming market. Beagles, Walkers, Plotts, English Setters, and various coon-hunting breeds all show up regularly during and after deer, bear, turkey, and small-game seasons for post-field cleanup, burr extraction, tick checks, and ear cleaning. The state's substantial outdoor culture also drives post-trail work for trail-active family pets, particularly in the Monongahela National Forest region and the New River Gorge area. The four-season climate with humid summers and snowy winters drives a predictable grooming cycle: spring deshedding for double-coated breeds, summer hot-spot management, fall tick-and-burr work, winter paw care for salt and slush in the urban areas. Tick exposure in heavily forested counties is significant. Pricing across West Virginia runs at the lower end of the national range, with most full-service grooms in the $35–$60 range for medium dogs. The Eastern Panhandle runs slightly higher, reflecting its DC-commuter economy. Mobile grooming exists but is limited by the state's mountainous geography."},
    {"name": "Wisconsin", "slug": "wisconsin", "abbr": "WI",
     "description": "Wisconsin's grooming industry is anchored by Milwaukee, Madison, and the Fox Cities-Green Bay corridor, with strong supporting markets in Eau Claire, La Crosse, Wausau, Kenosha-Racine, and the Door County resort community. Milwaukee and the surrounding Waukesha-Ozaukee-Washington county suburbs (Brookfield, Mequon, Oconomowoc, Brookfield, Wauwatosa) make up the largest market. Madison's grooming scene reflects its university-and-state-capital character, with an unusually deep concentration of independent boutique salons and force-free certified studios. The Fox Valley and Green Bay anchor northeastern Wisconsin. Wisconsin winters are cold, snowy, and long, with lake-effect bands hitting the eastern side of the state. Salt and chemical de-icers are used heavily in metro areas, and most experienced Wisconsin groomers handle paw rinses, paw balm applications, and trim-the-foot-feathers services for ice ball prevention as routine winter add-ons. Spring deshedding is heavy for the state's substantial population of double-coated breeds — Goldens, Labs, German Shepherds, Aussies, Bernese, Newfoundlands, plus the various working farm dogs common across rural Wisconsin. Summer brings lake swimming volume — the state has thousands of inland lakes plus Lake Michigan and Lake Superior shorelines — and the post-swim rinses to clear out lake water, algae, and sand. Hunting dogs (waterfowl retrievers, pheasant pointers, deer hounds) come in heavily during fall hunting seasons. Pricing across Wisconsin runs at standard Midwestern regional rates, with most full-service grooms in the $50–$90 range for medium dogs at metro salons. The wealthier Milwaukee and Madison neighborhoods run higher. Mobile grooming has expanded notably in both major metros."},
    {"name": "Wyoming", "slug": "wyoming", "abbr": "WY",
     "description": "Wyoming has the smallest population of any U.S. state and a correspondingly small grooming industry, but the state's working-dog culture, outdoor lifestyle, and harsh climate make professional grooming meaningful work for the operators who do it. Cheyenne is the largest market by population, with Casper, Laramie, Gillette, Rock Springs, Sheridan, and Cody as the main regional centers. Jackson and Teton County operate as a distinct premium-priced segment shaped by the resort and second-home economy — pricing in Jackson runs comparable to high-end Aspen and Park City markets. Working dogs are unusually well-represented in Wyoming. Ranch dogs (Aussies, Border Collies, Anatolian Shepherds, Great Pyrenees, Heelers), hunting dogs (Labs, German Shorthaired Pointers, English Setters, Brittanys), and the various working breeds used in oilfield and agricultural settings all show up regularly at Wyoming salons. Grooming work skews functional — full bath-and-blow services, undercoat raking, burr and seed-pod extraction, paw inspections, ear cleaning — rather than show-style breed cuts. Climate considerations are dominated by extremes: long, cold, windy winters with subzero stretches and aggressive de-icer use; short, dry summers with intense UV exposure at altitude; spring mud and shoulder-season weather swings. Spring deshedding is heavy for the state's substantial population of double-coated working breeds. Foxtails and seed pods are a serious threat in late summer. Pricing across most of Wyoming runs accessibly. Jackson and Teton County are the exception, with pricing well above the statewide average. Mobile grooming exists in Cheyenne and Casper but remains uncommon elsewhere."},
]

# Service categories (replaces splash pad feature filters)
CATEGORIES = [
    {"name": "Full-Service Grooming", "slug": "full-service", "icon": "✂️",
     "description": "Full-service groomers offering bath, cut, dry, nails, and styling",
     "intro": "Full-service dog groomers handle every aspect of your dog's grooming needs in a single appointment. A typical full-service session includes a bath with breed-appropriate shampoo, blow-dry, haircut or trim, nail clipping, ear cleaning, and sometimes teeth brushing. These groomers are trained to handle all breeds and coat types, from poodle show cuts to golden retriever deshedding. Full-service grooming is the most popular option for dog owners who want a one-stop professional experience."},
    {"name": "Mobile Grooming", "slug": "mobile-grooming", "icon": "🚐",
     "description": "Mobile groomers that come to your home in a fully equipped van",
     "intro": "Mobile dog groomers bring the salon to your doorstep in a fully equipped grooming van. This option is ideal for dogs that get anxious in grooming salons, elderly dogs that struggle with car rides, owners with multiple dogs, or anyone who values the convenience of at-home service. Mobile groomers typically offer the same full-service experience as brick-and-mortar salons — bath, cut, nails, ears — without the stress of a new environment for your pet."},
    {"name": "Breed-Specific Styling", "slug": "breed-specific", "icon": "🏆",
     "description": "Groomers specializing in breed-standard cuts and show grooming",
     "intro": "Breed-specific grooming goes beyond a basic haircut — these groomers are trained in the specific cut patterns, coat textures, and styling standards for individual breeds. Whether you need a proper poodle continental clip, a Schnauzer hand-strip, a Bichon round head, or a Cocker Spaniel skirt trim, breed-specific groomers deliver results that respect your dog's breed heritage. Many of these groomers have show ring experience and certifications."},
    {"name": "Cat Grooming Too", "slug": "cat-grooming", "icon": "🐱",
     "description": "Grooming shops that also handle cats and other pets",
     "intro": "Some grooming businesses specialize in more than just dogs — they also groom cats and occasionally other small pets. Cat grooming requires different handling techniques, specialized equipment, and patience for feline temperaments. If you have both dogs and cats, finding a groomer who handles both can simplify your pet care routine. These groomers are trained in feline coat types, lion cuts, and the unique needs of cat skin and fur."},
    {"name": "Puppy First Groom", "slug": "puppy-first-groom", "icon": "🐶",
     "description": "Groomers experienced with puppy introductions and first-time grooming",
     "intro": "A puppy's first grooming experience sets the tone for a lifetime of grooming visits. Groomers who specialize in puppy introductions use gentle handling, positive reinforcement, and shorter sessions to make the experience stress-free. They introduce puppies gradually to the sounds of clippers, the feel of water, and the grooming table. Starting with a skilled puppy groomer helps prevent grooming anxiety that can last years."},
    {"name": "Senior & Special Needs", "slug": "senior-special-needs", "icon": "🩺",
     "description": "Groomers experienced with elderly dogs and dogs with health conditions",
     "intro": "Senior dogs and dogs with special needs require extra care and patience during grooming. These groomers are experienced with arthritis accommodations, skin sensitivities, mobility challenges, and the gentle handling that older or health-compromised dogs need. They may offer padded tables, shorter sessions, breaks during grooming, and communication with your vet about skin conditions or medication that affects coat health."},
    {"name": "Self-Service Dog Wash", "slug": "self-service-wash", "icon": "🛁",
     "description": "Facilities where you wash your own dog using professional equipment",
     "intro": "Self-service dog wash stations give you access to professional grooming equipment — elevated tubs, warm water, professional shampoo, high-velocity dryers — without the mess at home. These are perfect for owners who enjoy bathing their own dog but don't want to deal with clogged drains and wet bathrooms. Most self-service facilities charge by the session and provide all the supplies you need."},
    {"name": "Affordable Grooming", "slug": "affordable", "icon": "💰",
     "description": "Budget-friendly groomers with transparent pricing",
     "intro": "Professional dog grooming doesn't have to break the bank. These groomers offer competitive pricing with transparent rates — no surprise upcharges for matting, size, or breed. Many offer package deals, loyalty discounts, or bath-only options for owners on a budget. Affordable doesn't mean low quality — these are professional groomers who keep their prices accessible so every dog can be well-groomed."},
]

# Google Analytics
GA_MEASUREMENT_ID = os.getenv("GA_MEASUREMENT_ID", "G-GLHVWDC9HQ")

# SEO Settings
DEFAULT_META_TITLE = "Dog Groomers Near Me | Local Dog Grooming Directory"
DEFAULT_META_DESCRIPTION = "Find dog groomers near you by state, city, service type, ratings, hours, prices, and reviews. Browse mobile, full-service, and affordable grooming."

# Build Settings
ITEMS_PER_PAGE = 24
FEATURED_COUNT = 6
RECENT_COUNT = 8
